### ISSUE TITLE
Extended-query protocol placeholder types

### ISSUE THREAD

**Issue by greshilov** [psycopg/psycopg3#22]
Hey, @dvarrazzo! First of all, thanks for your amazing work for the open source :)

I've recently discovered this brand new `psycopg3` repo and decided to participate a little bit with django backend driver #18. 

The first failed test I've tried to fix was `model_fields.test_uuid.TestQuerying.test_filter_with_expr`. It currently fails with following message:
```
django.db.utils.ProgrammingError: could not determine data type of parameter $1
```
The corresponding sql query from debug log is:  
```sql
SELECT 
   "model_fields_nullableuuidmodel"."id",
   "model_fields_nullableuuidmodel"."field", 
   CONCAT('8400', 'e29b') AS "value" 
FROM "model_fields_nullableuuidmodel" 
WHERE "model_fields_nullableuuidmodel"."field"::text LIKE '%%' 
   || REPLACE(REPLACE(REPLACE(CONCAT('8400', 'e29b'), E'\\', E'\\\\'), E'%%', E'\\%%'), E'_', E'\\_')
   || '%%'; args=('8400', 'e29b', '8400', 'e29b')
```

But where is `$1`? Well, `psycopg3` is internally converting all `python` like placeholders `%s` to `postgres` like `$1,$2`. Code can be found in `psycopg3.psycopg3._queries._query2pg` function. So if we manually print converted query from there it'll be:
```sql
SELECT 
  "model_fields_nullableuuidmodel"."id", 
  "model_fields_nullableuuidmodel"."field", 
  CONCAT($1, $2) AS "value" 
FROM "model_fields_nullableuuidmodel" 
WHERE "model_fields_nullableuuidmodel"."field"::text LIKE '%' 
   || REPLACE(REPLACE(REPLACE(CONCAT($3, $4), E'\\', E'\\\\'), E'%', E'\\%'), E'_', E'\\_') 
   || '%'
```

And that's the place where the problem lies! `psycopg3` uses extended-query protocol and thus requires more comprehensive type usage. Small example to understand difference between query and extended-query modes:

```python
import psycopg2
import psycopg3

QUERIES = (
    "SELECT REPLACE(CONCAT(%s, %s), 'foo', 'bar')",
    "SELECT REPLACE(CONCAT(%s::text, %s::text), 'foo', 'bar')"
)
PARAMS = ('foo', 'bar')

if __name__ == '__main__':
    for query in QUERIES:
        for psycopg in (psycopg2, psycopg3):
            conn = psycopg.connect("dbname=postgres user=postgres")
            cur = conn.cursor()
            try:
                cur.execute(query, PARAMS)
            except Exception as e:
                print(f'{psycopg.__name__} query {query!r} failed with exception: {e!r}')
            else:
                res = cur.fetchall()
                print(f'{psycopg.__name__} query {query!r} result is {res!r}')
            cur.close()
```
```log
psycopg2 query "SELECT REPLACE(CONCAT(%s, %s), 'foo', 'bar')" result is [('barbar',)]
psycopg3 query "SELECT REPLACE(CONCAT(%s, %s), 'foo', 'bar')" failed with exception: IndeterminateDatatype('could not determine data type of parameter $1')
psycopg2 query "SELECT REPLACE(CONCAT(%s::text, %s::text), 'foo', 'bar')" result is [('barbar',)]
psycopg3 query "SELECT REPLACE(CONCAT(%s::text, %s::text), 'foo', 'bar')" result is [('barbar',)]
```

Several questions here:  
 
1. Shall we log transformed queries somehow? It would have saved me a lot of time in this case.
2. What is desirable strategy for adding `::text` like type casts here? Is it user's responsibility, or `_query2pg` has to handle it?

**Comment by dvarrazzo** [comment]
Hello, thank you for looking into this.

Have you started from where I left? Just to know if this is one of the differences I had already tackled or if it was ahead.

The problem behind this specific cast is because text is - unexpectedly - passed as unknown, not as text, by psycopg3. The reason is explained [here](https://www.varrazzo.com/blog/2020/11/07/psycopg3-adaptation/) I didn't expect this failure though: I checked why, and it's likely because `concat()` arguments are defined as `VARIADIC any` in Postgres, not as text.

```
piro=# \df *.concat
                          List of functions
   Schema   |  Name  | Result data type | Argument data types | Type 
------------+--------+------------------+---------------------+------
 pg_catalog | concat | text             | VARIADIC "any"      | func
(1 row)
```

Most of the time I found these differences I could solve them by making the Django backend create the placeholders with added cast: where the psycopg2 backend generates `CONCAT(%s, %s)` the psycopg3 one should generate `CONCAT(%s::text, %s::text)`.  See this commit for instance: https://github.com/dvarrazzo/django/commit/215d2e3fc2224e4e8bce74992657063f60214927

From a cursory look at my commits in the django repos, things might have changed a bit in psycopg3 since (but not regards this topic: for instance I dropped `cursor.callproc()`). So if you find anything unexpected please let me know: I'm happy to give support for this Django driver and I appreciate your interest.

Cheers!

**Comment by greshilov** [comment]
Thank you for shedding the light on the library behaviour!

I started from dvarrazzo/django@12280d71f1f5b6b078fd730e48dd84976e45b85f, which looks like the very last commit in psycopg3 branch. 

I created a little PR with proposed `CONCAT(%s, %s) -> CONCAT(%s::text, %s::text)` conversion: https://github.com/dvarrazzo/django/pull/1. Hope it helps :)

Cheers!

**Comment by dvarrazzo** [comment]
> Shall we log transformed queries somehow? It would have saved me a lot of time in this case.

Note that you can find `query` and `params` as attributes on the cursor, if you need them.

**Comment by greshilov** [comment]
> > Shall we log transformed queries somehow? It would have saved me a lot of time in this case.
> 
> Note that you can find `query` and `params` as attributes on the cursor, if you need them.

Thanks for the tip!
