### ISSUE TITLE
Gevent Support

### ISSUE THREAD

**Issue by 3ddi** [psycopg/psycopg3#4]
Is it planed for this package work in gevent based projects or will it be totally async-await based like `asyncpg`?

**Comment by dvarrazzo** [comment]
The package is designed to operate with different concurrency models, not only with async. For a gevent program, the "normal" blocking behaviour is ok as long as blocking is collaborative: if your greenlet runs `cur.execute("select pg_sleep(1)")`, it is expected that it will get stuck for one second before getting the result of the function call, but that concurrent greenlets are free to run in the meantime.

In psycopg3 I am taking care of isolating the "wait to get this result" into a single place, currently the [`waiting.wait()`](https://github.com/psycopg/psycopg3/blob/ae8a43bc527b1b06d724386576e07623b49826ca/psycopg3/waiting.py#L32-L58) function, used both for connection and for querying. The current implementation uses the [`selectors`](https://docs.python.org/3.6/library/selectors.html) library, which I see [is patched by gevent](https://www.gevent.org/api/gevent.monkey.html#gevent.monkey.patch_select): this should mean that psycopg3 should work out-of-the-box with gevent.

One step back: psycopg2 had the need of a "psycogreen" package and internally had a "green mode" to work. The cause of this was that the normal blocking psycopg2 had the waiting done not only in the C code, but not even by psycopg code itself, rather by the libpq, using blocking calls. In order to support gevent and eventlet we had to create a "green path", enabled by registering a [wait callback](https://www.psycopg.org/docs/extensions.html#psycopg2.extensions.set_wait_callback) which:

- changes what libpq function used, using non-blocking ones,
- invoke the Python wait callback from the C code whenever there is need to wait.

How to wait, in psycopg2, is delegated to gevent, or eventlet, or select, according to the wait callback used.

psycopg3 we may say it only works in green mode: it uses no blocking libpq call in the normal connection and querying processing. At the moment the waiting code is in Python so monkeypatching already works. Just tested with this program, connecting 3 connections and waiting for three queries, each one taking 2 seconds:

```python
import gevent
from gevent import monkey
monkey.patch_all()

import logging
import psycopg3

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")

def worker1(ident, secs):
    logging.info("connecting %s", ident)
    conn = psycopg3.connect("")
    cur = conn.cursor()
    logging.info("querying %s", ident)
    cur.execute("select pg_sleep(%s)", (secs,))
    logging.info("queried %s", ident)
    cur.close()
    conn.close()

logging.info("start threads")
threads = [gevent.spawn(worker1, i, 2) for i in range(3)]
gevent.joinall(threads)
logging.info("end threads")
```

Running the program shows collaborative behaviour: as soon as the first greenlet starts to wait for a connection it gives the possibility to the second to connect too; queries start when another query is already in progress, so the program take eventually 2 seconds to complete.

```
2020-05-24 13:47:29,883 start threads
2020-05-24 13:47:29,883 connecting 0
2020-05-24 13:47:29,884 connecting 1
2020-05-24 13:47:29,885 connecting 2
2020-05-24 13:47:29,887 querying 0
2020-05-24 13:47:29,888 querying 2
2020-05-24 13:47:29,889 querying 1
2020-05-24 13:47:31,892 queried 0
2020-05-24 13:47:31,893 queried 1
2020-05-24 13:47:31,894 queried 2
```

if you comment out the `monkey.patch_all()` call, the program becomes sequential and takes 6 seconds to complete:

```
2020-05-24 13:47:51,038 start threads
2020-05-24 13:47:51,039 connecting 0
2020-05-24 13:47:51,043 querying 0
2020-05-24 13:47:53,047 queried 0
2020-05-24 13:47:53,047 connecting 1
2020-05-24 13:47:53,050 querying 1
2020-05-24 13:47:55,052 queried 1
2020-05-24 13:47:55,053 connecting 2
2020-05-24 13:47:55,060 querying 2
2020-05-24 13:47:57,064 queried 2
2020-05-24 13:47:57,065 end threads
```

psycopg3 also offers a concurrency model based on asyncio but that's explicitly chosen by using a different connection class and requires a different interface (you would have to call `await cur.execute(...)`)

Going forward maybe a tighter integration with the reactor could be beneficial: from the results [shown here](https://www.varrazzo.com/blog/2020/05/19/a-trip-into-optimisation/) it seems that there is performance to gain by using the I/O completion facilities at a lower level; however I'm still interested in making them accessible/patchable by gevent/eventlet/greenlets.

**Comment by 3ddi** [comment]
Thank you very much for the detailed answer! :)
